cncf/telecom-user-group

- README.md
- Next zoom call: Monday, July 15th at 3:00PM UTC (8AM PT)
- ONS EU half day
- KubeCon NA Intro+Deep dive
> update next meeting, add upcoming events

- README.md
Tutorial: Take a Test Drive with the Cloud Native Network Function (CNF) Testbed - Sponsored by Cloud Native Computing Foundation (Pre-registration required)
> update ONSEU19 tutorial name

- README.md
- adjacent-communities.md
The start of a description of adjacent communities the CNCF TUG
works with.
> Adding adjacent commuities

- README.md
Agh, sorry. I forgot the add the link.
> Adding a link to the adjacent communities page.

- README.md
Next zoom call: Monday, October 7th at 3:00 - 4:00 PM UTC (8:00 - 9:00 AM Pacific Time)
> update next meeting time, upcoming events

- README.md
Updated - **Next zoom call: Monday, December 2nd at 4:00 - 5:00 PM UTC (8:00 - 9:00 AM Pacific Time)**
Added  - [RSVP, space is limited](https://forms.gle/VahVc9WVPNGMdk9p9)
@taylor
> next zoom call Dec 2, RSVP TUG & CNTT meetings

- README.md
- **Next zoom call: Monday, December 16th at 11:00 - 12:00 UTC (7:00 - 8:00 PM China Standard Time)**
> update Next zoom call

- README.md
- **Next zoom call: Monday, January 6th at 16:00 - 17:00 UTC (8:00 - 9:00 AM Pacific Time)**
@taylor
> update next meeting

- README.md
- next TUG call on Mon, Jan 20
- added KubeCon EU to upcoming events
@taylor Please review and merge
> update next meeting and events

- README.md
- **Next zoom call: Monday, February 3rd at 4:00 - 5:00 PM UTC (8:00 - 9:00 AM Pacific Time)**  
@taylor please review and merge
> add next zoom call to README

- whitepaper/readme.md
Add chapter 1 google doc link to the white paper markdown
> Chapter 1 link

- README.md
adds Feb 17th, MWC, KubeCon EU, ONES NA to README
@taylor please review
> update next zoom and upcoming events

- README.md
- whitepaper/readme.md
- added to top level readme
- added to whitepaper readme
> Added License section to readme covering CCBY4.0

- adjacent-communities.md
- Removing the Antwerp f2f
- Adding LA f2f
> Update of CNTT events

- whitepaper/cloud_native_thinking_for_telecommunications.md
Regarding https://github.com/cncf/telecom-user-group/issues/44
> Explicitly stating that a Serving Gateway can be implemented as a CNF

- CONTRIBUTING.md
> Update of CONTRIBUTING based on the discussion on Issue #42

- README.md
Update "Next zoom call" and "Upcoming Events" in README.md
> next meeting on Mon, Mar 16th, events TBD

- README.md
Next zoom call: Monday, April 20th at 11:00AM UTC (7:00PM China Standard Time)
> update next zoom call day/time

- README.md
Tuesday, September 29 • 2:55pm - 3:25pm - [Birds of a Feather: CNCF Telecom User Group](https://sched.co/bWQV)
> add ONES schedule to upcoming events

- README.md
- **Next zoom call: Monday, May 18th at 11:00 UTC (7:00 PM China Standard Time)**
> update next TUG call, upcoming events

- README.md
- **Next zoom call: Monday, July 6th at 11:00 UTC (7pm China Standard Time)**
> update next meeting time

- README.md
- **Next zoom call: Monday, August 3rd at 15:00 UTC (8am Pacific Time)**  
Saturday, August 1 • 12:10 - 12:40 UTC - [Intro: Birds of a Feather: Telecom User Group](https://sched.co/cpAM)
Wednesday, August 19 • 14:55 - 16:15 UTC - [Birds of a Feather: Telecom User Group](https://sched.co/Zevr)
> update next meeting and upcoming events

- README.md
Wednesday, August 19 • 14:55 - 15:30 UTC - [Birds of a Feather: Telecom User Group](https://sched.co/Zevr)
Wednesday, September 30 • 17:45 - 18:15 UTC - [Birds of a Feather: CNCF Telecom User Group](https://sched.co/bWQV)
Wednesday, September 30 • 17:45 - 18:15 UTC - [Panel Discussion: Cloud Native Thinking for Telecommunications Chapter 1](https://sched.co/bWQh)
> update upcoming events

- README.md
- **Next zoom call: Monday, December 7th at 15:00 UTC**
> update meeting time for December

- README.md
- next call on Mon, Jan 4 at 11:00 UTC
> next call on Mon, Jan 4 at 11:00 UTC

- README.md
Added Feb 1 TUG day/time & KubeCon EU 2021 TBD
> Added Feb 1 TUG & KubeCon EU 2021

- README.md
- **Next zoom call: Monday, March 1st at 11:00 UTC**
> next TUG on Mon, March 1

- README.md
No meeting on Mon, July 5th due to US Independence Day (observed federal holiday)
> next TUG meeting on Aug 2nd

- README.md
- Next zoom call: Monday, December 6th at 15:00 UTC (7am Pacific Standard Time)
> Next TUG on Monday, December 6th at 15:00 UTC

- README.md
- **Next zoom call: Monday, February 7th, 2022 at 15:00 UTC (7am Pacific Standard Time)**
> update next meeting date
